/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author victortrimpai
 */
public class VistaColaborador extends javax.swing.JFrame {

    /**
     * Creates new form VistaColaborador
     */
    public VistaColaborador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        background2 = new javax.swing.JLabel();
        Colaborador = new javax.swing.JLabel();
        bEntrada = new javax.swing.JButton();
        bSalida = new javax.swing.JButton();
        bPreLiquidacion = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        Asistencia = new javax.swing.JLabel();
        PreLiquidacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/city.png"))); // NOI18N

        Colaborador.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        Colaborador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Colaborador.setText("Bienvenido Colaborador");

        bEntrada.setBackground(new java.awt.Color(255, 255, 255));
        bEntrada.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        bEntrada.setText("Registro Entrada");
        bEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        bSalida.setBackground(new java.awt.Color(255, 255, 255));
        bSalida.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        bSalida.setText("Registro Salida");
        bSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        bPreLiquidacion.setBackground(new java.awt.Color(255, 255, 255));
        bPreLiquidacion.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        bPreLiquidacion.setText("Pre-Visualizar");
        bPreLiquidacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        bSalir.setBackground(new java.awt.Color(255, 255, 255));
        bSalir.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        bSalir.setText("Cerrar Sesion");
        bSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        Asistencia.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        Asistencia.setText("Asistencia");

        PreLiquidacion.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        PreLiquidacion.setText("Pre Liquidacion");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(background2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(266, 266, 266)
                                .addComponent(Asistencia))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(214, 214, 214)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bPreLiquidacion, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(246, 246, 246)
                                .addComponent(PreLiquidacion)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(Colaborador)
                        .addGap(0, 195, Short.MAX_VALUE))))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(background2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Colaborador)
                .addGap(30, 30, 30)
                .addComponent(Asistencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(PreLiquidacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bPreLiquidacion, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login L = new Login();
        L.setVisible(true);
    }//GEN-LAST:event_bSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaColaborador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Asistencia;
    private javax.swing.JLabel Colaborador;
    private javax.swing.JLabel PreLiquidacion;
    private javax.swing.JButton bEntrada;
    private javax.swing.JButton bPreLiquidacion;
    private javax.swing.JButton bSalida;
    private javax.swing.JButton bSalir;
    private javax.swing.JPanel background;
    private javax.swing.JLabel background2;
    // End of variables declaration//GEN-END:variables
}
