package Vista;

import Datos.DatoAsistencia;
import Datos.DatoFormulario;
import Entidades.Asistencia;
import Entidades.Empleado;
import Negocio.NegocioAsistencia;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victortrimpai
 */
public class VistaColaborador extends javax.swing.JFrame {

    /**
     * Creates new form VistaColaborador
     */    
    String VariableBonita = null;
    public VistaColaborador() {
    initComponents();
    }
    public VistaColaborador(String usuarioSesion) {
        initComponents();
        VariableBonita = usuarioSesion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        background2 = new javax.swing.JLabel();
        Colaborador = new javax.swing.JLabel();
        bEntrada = new javax.swing.JButton();
        bSalida = new javax.swing.JButton();
        jbPreview = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        Asistencia = new javax.swing.JLabel();
        PreLiquidacion = new javax.swing.JLabel();
        jPanelDatos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAsistencia = new javax.swing.JTable();
        jPanelDatos1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPreLiquidacion = new javax.swing.JTable();
        lblColaborador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/city.png"))); // NOI18N

        Colaborador.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        Colaborador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Colaborador.setText("Bienvenido");

        bEntrada.setBackground(new java.awt.Color(255, 255, 255));
        bEntrada.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        bEntrada.setText("Registro Entrada");
        bEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEntradaActionPerformed(evt);
            }
        });

        bSalida.setBackground(new java.awt.Color(255, 255, 255));
        bSalida.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        bSalida.setText("Registro Salida");
        bSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalidaActionPerformed(evt);
            }
        });

        jbPreview.setBackground(new java.awt.Color(255, 255, 255));
        jbPreview.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jbPreview.setText("Pre-Visualizar");
        jbPreview.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPreviewActionPerformed(evt);
            }
        });

        bSalir.setBackground(new java.awt.Color(255, 255, 255));
        bSalir.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        bSalir.setText("Cerrar Sesion");
        bSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        Asistencia.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        Asistencia.setText("Asistencia:");

        PreLiquidacion.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        PreLiquidacion.setText("PreLiquidacion:");

        jPanelDatos.setBackground(new java.awt.Color(245, 255, 255));
        jPanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        tablaAsistencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Fecha", "Hora Entrada", "Hora Salida"
            }
        ));
        jScrollPane1.setViewportView(tablaAsistencia);

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelDatos1.setBackground(new java.awt.Color(245, 255, 255));
        jPanelDatos1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        tblPreLiquidacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Dias Trabajados", "Sueldo Base", "Bono Asistencia", "Bono Responsabilidad", "Desc. AFP", "Desc. Salud", "Sueldo Bruto", "Sueldo Liquido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPreLiquidacion.setEnabled(false);
        tblPreLiquidacion.setRowHeight(79);
        tblPreLiquidacion.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(tblPreLiquidacion);

        javax.swing.GroupLayout jPanelDatos1Layout = new javax.swing.GroupLayout(jPanelDatos1);
        jPanelDatos1.setLayout(jPanelDatos1Layout);
        jPanelDatos1Layout.setHorizontalGroup(
            jPanelDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatos1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanelDatos1Layout.setVerticalGroup(
            jPanelDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatos1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblColaborador.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lblColaborador.setText("jLabel1");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(background2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanelDatos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(Asistencia)
                                        .addGap(18, 18, 18)
                                        .addComponent(bEntrada)
                                        .addGap(18, 18, 18)
                                        .addComponent(bSalida))
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(PreLiquidacion)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbPreview))
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addGap(187, 187, 187)
                                        .addComponent(Colaborador)
                                        .addGap(26, 26, 26)
                                        .addComponent(lblColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(bSalir)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(background2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Colaborador)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(lblColaborador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGap(24, 24, 24)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Asistencia)
                    .addComponent(bEntrada)
                    .addComponent(bSalida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PreLiquidacion)
                    .addComponent(jbPreview))
                .addGap(18, 18, 18)
                .addComponent(jPanelDatos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(bSalir)
                .addContainerGap())
        );

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login L = new Login();
        L.setVisible(true);
    }//GEN-LAST:event_bSalirActionPerformed

    private void bEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEntradaActionPerformed
 
        Date FechaActual = new Date();
        Asistencia a = new Asistencia();
        a.setFecha(FechaActual);
        a.setHoraEntrada(FechaActual);
        a.setIdEmpleado(Integer.parseInt(VariableBonita));

        NegocioAsistencia na = new NegocioAsistencia();
        boolean respuesta = na.InsertarAsistencia(a);


    }//GEN-LAST:event_bEntradaActionPerformed

    private void bSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalidaActionPerformed

        Date FechaActual = new Date();

        Asistencia a = new Asistencia();
        a.setHoraSalida(FechaActual);
        a.setIdEmpleado(Integer.parseInt(VariableBonita));

        NegocioAsistencia na = new NegocioAsistencia();
        boolean respuesta = na.InsertarSalida(a);
        
    }//GEN-LAST:event_bSalidaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        lblColaborador.setText(VariableBonita);
        
        DefaultTableModel tblAsistencia = new DefaultTableModel();
        tablaAsistencia.setModel(tblAsistencia);
        tblAsistencia.addColumn("id");
        tblAsistencia.addColumn("Fecha");
        tblAsistencia.addColumn("Hora Entrada");
        tblAsistencia.addColumn("Hora Salida");
        
        DatoAsistencia operacion = new DatoAsistencia();
        List<Asistencia> datos = operacion.Asistencia(Integer.parseInt(VariableBonita));
        Iterator it = datos.iterator();
        while (it.hasNext()) {
            Asistencia a = (Asistencia) it.next();
            Object[] fila = new Object[4];

            fila[0] = a.getIdEmpleado();
            fila[1] = a.getFecha();
            fila[2] = a.getHoraEntrada();
            fila[3] = a.getHoraSalida();

            tblAsistencia.addRow(fila);
           
       }
//
//        JOptionPane.showMessageDialog(null, "Lista cargada con exito", "", WIDTH);
//        
    }//GEN-LAST:event_formWindowOpened

    private void jbPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPreviewActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblPreview = new DefaultTableModel();
        tblPreLiquidacion.setModel(tblPreview);
        tblPreview.addColumn("Id");
        tblPreview.addColumn("Nombre");
        tblPreview.addColumn("Dias Trabajados");
        tblPreview.addColumn("Sueldo Base");
        tblPreview.addColumn("Bono Asistencia");
        tblPreview.addColumn("Bono Responsabilidad");
        tblPreview.addColumn("Desc. AFP");
        tblPreview.addColumn("Desc. Salud");
        tblPreview.addColumn("Sueldo Bruto");
        tblPreview.addColumn("Sueldo Líquido");
        
        DatoAsistencia Da = new DatoAsistencia();
        DatoFormulario Df = new DatoFormulario();
        List<Asistencia> datos = Da.Asistencia(Integer.parseInt(VariableBonita));
//        System.out.println(Da.CountAsistencia(Integer.parseInt(VariableBonita)));
        List<Empleado> datos2 = Df.DatoEmpleado(Integer.parseInt(VariableBonita));
        Empleado e = new Empleado(); 

        if (datos2.size() >=0 ){
            e = datos2.get(0);
        }
        Iterator it = datos.iterator();
        for (int i = 0; i < 1; i++){
            Asistencia a = (Asistencia) it.next();
            Object[] fila = new Object[10];

            fila[0] = a.getIdEmpleado();
            fila[1] = e.getNombre();
            Long DiasTrabajados = Da.CountAsistencia(Integer.parseInt(VariableBonita));
            fila[2] = DiasTrabajados;
            fila[3] = e.getSueldoBase();
            int BonoAsistencia = 30000;
            fila[4] = BonoAsistencia;
            int BonoResponsabilidad = 20000;
            fila[5] = BonoResponsabilidad;
            double DescAFP = e.getSueldoBase()*0.12;
            fila[6] = DescAFP;
            double DescSalud = e.getSueldoBase()*0.10;
            fila[7] = DescSalud;
            int SueldoBruto = e.getSueldoBase()+BonoAsistencia+BonoResponsabilidad;
            fila[8] = SueldoBruto;
            double SueldoLiquido = SueldoBruto-DescAFP-DescSalud;
            fila[9] = SueldoLiquido;

            tblPreview.addRow(fila);
           
       }
    }//GEN-LAST:event_jbPreviewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaColaborador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Asistencia;
    private javax.swing.JLabel Colaborador;
    private javax.swing.JLabel PreLiquidacion;
    private javax.swing.JButton bEntrada;
    private javax.swing.JButton bSalida;
    private javax.swing.JButton bSalir;
    private javax.swing.JPanel background;
    private javax.swing.JLabel background2;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelDatos1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbPreview;
    private javax.swing.JLabel lblColaborador;
    private javax.swing.JTable tablaAsistencia;
    private javax.swing.JTable tblPreLiquidacion;
    // End of variables declaration//GEN-END:variables
}
