package Vista;

import Entidades.AsistenciaEntrada;
import Entidades.AsistenciaSalida;
import Negocio.EntradaAsistencia;
import Negocio.SalidaAsistencia;
import java.util.Date;

/**
 *
 * @author victortrimpai
 */
public class VistaColaborador extends javax.swing.JFrame {

    /**
     * Creates new form VistaColaborador
     */
    public VistaColaborador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        background2 = new javax.swing.JLabel();
        Colaborador = new javax.swing.JLabel();
        bEntrada = new javax.swing.JButton();
        bSalida = new javax.swing.JButton();
        bPreLiquidacion = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        Asistencia = new javax.swing.JLabel();
        PreLiquidacion = new javax.swing.JLabel();
        jPanelDatos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAsistencia = new javax.swing.JTable();
        jPanelDatos1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAsistencia1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/city.png"))); // NOI18N

        Colaborador.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        Colaborador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Colaborador.setText("Bienvenido Colaborador");

        bEntrada.setBackground(new java.awt.Color(255, 255, 255));
        bEntrada.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        bEntrada.setText("Registro Entrada");
        bEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEntradaActionPerformed(evt);
            }
        });

        bSalida.setBackground(new java.awt.Color(255, 255, 255));
        bSalida.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        bSalida.setText("Registro Salida");
        bSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalidaActionPerformed(evt);
            }
        });

        bPreLiquidacion.setBackground(new java.awt.Color(255, 255, 255));
        bPreLiquidacion.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        bPreLiquidacion.setText("Pre-Visualizar");
        bPreLiquidacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        bSalir.setBackground(new java.awt.Color(255, 255, 255));
        bSalir.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        bSalir.setText("Cerrar Sesion");
        bSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        Asistencia.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        Asistencia.setText("Asistencia:");

        PreLiquidacion.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        PreLiquidacion.setText("PreLiquidacion:");

        jPanelDatos.setBackground(new java.awt.Color(245, 255, 255));
        jPanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        tablaAsistencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Fecha", "Hora Entrada", "Hora Salida"
            }
        ));
        jScrollPane1.setViewportView(tablaAsistencia);

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelDatos1.setBackground(new java.awt.Color(245, 255, 255));
        jPanelDatos1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        tablaAsistencia1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Dias Trabajados", "Sueldo Base", "Bono Asistencia", "Bono Responsabilidad", "Desc. AFP", "Desc. Salud", "Sueldo Bruto", "Sueldo Liquido"
            }
        ));
        jScrollPane2.setViewportView(tablaAsistencia1);

        javax.swing.GroupLayout jPanelDatos1Layout = new javax.swing.GroupLayout(jPanelDatos1);
        jPanelDatos1.setLayout(jPanelDatos1Layout);
        jPanelDatos1Layout.setHorizontalGroup(
            jPanelDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatos1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanelDatos1Layout.setVerticalGroup(
            jPanelDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatos1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(background2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addGap(187, 187, 187)
                                        .addComponent(Colaborador))
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(Asistencia)
                                        .addGap(18, 18, 18)
                                        .addComponent(bEntrada)
                                        .addGap(18, 18, 18)
                                        .addComponent(bSalida))
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(PreLiquidacion)
                                        .addGap(18, 18, 18)
                                        .addComponent(bPreLiquidacion)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanelDatos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(bSalir)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(background2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Colaborador)
                .addGap(24, 24, 24)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Asistencia)
                    .addComponent(bEntrada)
                    .addComponent(bSalida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PreLiquidacion)
                    .addComponent(bPreLiquidacion))
                .addGap(18, 18, 18)
                .addComponent(jPanelDatos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(bSalir)
                .addContainerGap())
        );

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login L = new Login();
        L.setVisible(true);
    }//GEN-LAST:event_bSalirActionPerformed

    private void bEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEntradaActionPerformed
        // Registro engtrada asistencia

        Date FechaActual = new Date();

        AsistenciaEntrada a = new AsistenciaEntrada();
        a.setFecha(FechaActual);
        a.setHoraEntrada(FechaActual);
        a.setIdEmpleado(23778674);

        EntradaAsistencia na = new EntradaAsistencia();
        boolean respuesta = na.EntradaAsistencia(a);


    }//GEN-LAST:event_bEntradaActionPerformed

    private void bSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalidaActionPerformed
        // registro de salida
        
        Date FechaActual = new Date();

        AsistenciaSalida a = new AsistenciaSalida();
        a.setFecha(FechaActual);
        a.setHoraSalida(FechaActual);
        a.setIdEmpleado(23778674);

        SalidaAsistencia na = new SalidaAsistencia();
        boolean respuesta = na.SalidaAsistencia(a);
    }//GEN-LAST:event_bSalidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaColaborador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Asistencia;
    private javax.swing.JLabel Colaborador;
    private javax.swing.JLabel PreLiquidacion;
    private javax.swing.JButton bEntrada;
    private javax.swing.JButton bPreLiquidacion;
    private javax.swing.JButton bSalida;
    private javax.swing.JButton bSalir;
    private javax.swing.JPanel background;
    private javax.swing.JLabel background2;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelDatos1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaAsistencia;
    private javax.swing.JTable tablaAsistencia1;
    // End of variables declaration//GEN-END:variables
}
