package Entidades;
// Generated 27-nov-2022 18:09:56 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AsistenciaSalida generated by hbm2java
 */
public class AsistenciaSalida  implements java.io.Serializable {


     private int idEmpleado;
     private Date fecha;
     private Date horaSalida;

    public AsistenciaSalida() {
    }

	
    public AsistenciaSalida(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public AsistenciaSalida(int idEmpleado, Date fecha, Date horaSalida) {
       this.idEmpleado = idEmpleado;
       this.fecha = fecha;
       this.horaSalida = horaSalida;
    }
   
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(Date horaSalida) {
        this.horaSalida = horaSalida;
    }




}


