package Entidades;
// Generated 27-nov-2022 18:09:56 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AsistenciaEntrada generated by hbm2java
 */
public class AsistenciaEntrada  implements java.io.Serializable {


     private int idEmpleado;
     private Date fecha;
     private Date horaEntrada;

    public AsistenciaEntrada() {
    }

	
    public AsistenciaEntrada(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public AsistenciaEntrada(int idEmpleado, Date fecha, Date horaEntrada) {
       this.idEmpleado = idEmpleado;
       this.fecha = fecha;
       this.horaEntrada = horaEntrada;
    }
   
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHoraEntrada() {
        return this.horaEntrada;
    }
    
    public void setHoraEntrada(Date horaEntrada) {
        this.horaEntrada = horaEntrada;
    }




}


