package Entidades;
// Generated 27-nov-2022 18:09:56 by Hibernate Tools 4.3.1



/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int idEmpleado;
     private String nombre;
     private int edad;
     private String direccion;
     private String email;
     private String comuna;
     private int numeroTelefonico;
     private String nombreCargo;
     private Integer sueldoBase;

    public Empleado() {
    }

	
    public Empleado(int idEmpleado, String nombre, int edad, String direccion, String email, String comuna, int numeroTelefonico, String nombreCargo) {
        this.idEmpleado = idEmpleado;
        this.nombre = nombre;
        this.edad = edad;
        this.direccion = direccion;
        this.email = email;
        this.comuna = comuna;
        this.numeroTelefonico = numeroTelefonico;
        this.nombreCargo = nombreCargo;
    }
    public Empleado(int idEmpleado, String nombre, int edad, String direccion, String email, String comuna, int numeroTelefonico, String nombreCargo, Integer sueldoBase) {
       this.idEmpleado = idEmpleado;
       this.nombre = nombre;
       this.edad = edad;
       this.direccion = direccion;
       this.email = email;
       this.comuna = comuna;
       this.numeroTelefonico = numeroTelefonico;
       this.nombreCargo = nombreCargo;
       this.sueldoBase = sueldoBase;
    }
   
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getComuna() {
        return this.comuna;
    }
    
    public void setComuna(String comuna) {
        this.comuna = comuna;
    }
    public int getNumeroTelefonico() {
        return this.numeroTelefonico;
    }
    
    public void setNumeroTelefonico(int numeroTelefonico) {
        this.numeroTelefonico = numeroTelefonico;
    }
    public String getNombreCargo() {
        return this.nombreCargo;
    }
    
    public void setNombreCargo(String nombreCargo) {
        this.nombreCargo = nombreCargo;
    }
    public Integer getSueldoBase() {
        return this.sueldoBase;
    }
    
    public void setSueldoBase(Integer sueldoBase) {
        this.sueldoBase = sueldoBase;
    }




}


