package Entidades;
// Generated 24-nov-2022 2:31:21 by Hibernate Tools 4.3.1



/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private int idEmpleado;
     private String nombre;
     private int edad;
     private String direccion;
     private String email;
     private String comuna;
     private Integer codEmpresa;
     private int numeroTelefonico;

    public Empleados() {
    }

	
    public Empleados(int idEmpleado, String nombre, int edad, String direccion, String email, String comuna, int numeroTelefonico) {
        this.idEmpleado = idEmpleado;
        this.nombre = nombre;
        this.edad = edad;
        this.direccion = direccion;
        this.email = email;
        this.comuna = comuna;
        this.numeroTelefonico = numeroTelefonico;
    }
    public Empleados(int idEmpleado, String nombre, int edad, String direccion, String email, String comuna, Integer codEmpresa, int numeroTelefonico) {
       this.idEmpleado = idEmpleado;
       this.nombre = nombre;
       this.edad = edad;
       this.direccion = direccion;
       this.email = email;
       this.comuna = comuna;
       this.codEmpresa = codEmpresa;
       this.numeroTelefonico = numeroTelefonico;
    }
   
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getComuna() {
        return this.comuna;
    }
    
    public void setComuna(String comuna) {
        this.comuna = comuna;
    }
    public Integer getCodEmpresa() {
        return this.codEmpresa;
    }
    
    public void setCodEmpresa(Integer codEmpresa) {
        this.codEmpresa = codEmpresa;
    }
    public int getNumeroTelefonico() {
        return this.numeroTelefonico;
    }
    
    public void setNumeroTelefonico(int numeroTelefonico) {
        this.numeroTelefonico = numeroTelefonico;
    }




}


