package Entidades;
// Generated 24-nov-2022 2:31:21 by Hibernate Tools 4.3.1



/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private int idEmpresa;
     private String nombre;
     private String direccion;
     private String comuna;
     private String ciudad;

    public Empresa() {
    }

	
    public Empresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public Empresa(int idEmpresa, String nombre, String direccion, String comuna, String ciudad) {
       this.idEmpresa = idEmpresa;
       this.nombre = nombre;
       this.direccion = direccion;
       this.comuna = comuna;
       this.ciudad = ciudad;
    }
   
    public int getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getComuna() {
        return this.comuna;
    }
    
    public void setComuna(String comuna) {
        this.comuna = comuna;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }




}


