package Entidades;
// Generated 02-dic-2022 15:08:20 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private Integer idEmpleado;
     private Integer pass;

    public Usuario() {
    }

	
    public Usuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuario(int idUsuario, Integer idEmpleado, Integer pass) {
       this.idUsuario = idUsuario;
       this.idEmpleado = idEmpleado;
       this.pass = pass;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Integer getPass() {
        return this.pass;
    }
    
    public void setPass(Integer pass) {
        this.pass = pass;
    }




}


